Repository team-aliens/DMS-iOS, pull requests merged in 2022-10, with the labels that each got.

#35 merge :: DMSCheckBox
  Projects/UsertInterfaces/DesignSystem/Sources/CheckBox/DMSCheckBox.swift
  Projects/UsertInterfaces/DesignSystem/Sources/CheckBox/DMSCheckBoxStyle.swift
Labels: ✨feat

#36 merge :: 디자인 시스템의 View들을 모아서 볼 수 있는 View를 만듭니다
  Projects/App/Sources/Application/DMSApp.swift
  Projects/UsertInterfaces/DesignSystem/Sources/CheckBox/DMSCheckBoxStyle.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Extensions/View+if.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Playground/DesignSystemPlaygroundView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Playground/Views/ButtonPlaygroundView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Playground/Views/CheckboxPlaygroundView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Playground/Views/ColorPlaygroundView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Playground/Views/FontPlaygroundView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Playground/Views/RadiobuttonPlaygroundView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Playground/Views/SwitchPlaygroundView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Playground/Views/TextFieldPlaygroundView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/RadioButton/DMSRadioButton.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Typography/DMSFontStyle.swift
Labels: ✨feat

#37 🔀 :: 앱 실행 시 나오는 경고 로그 삭제
  Projects/App/Support/Info.plist
  Projects/UsertInterfaces/DesignSystem/Sources/RadioButton/DMSRadioButton.swift
Labels: 👾bug

#40 merge :: CommonFeature의 이름을 BaseFeature로 변경
  Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
  Projects/App/Project.swift
  Projects/Features/BaseFeature/Derived/InfoPlists/BaseFeature-Info.plist
  Projects/Features/BaseFeature/Derived/InfoPlists/BaseFeatureTests-Info.plist
  Projects/Features/BaseFeature/Project.swift
  Projects/Features/BaseFeature/Sources/Feature.swift
  Projects/Features/BaseFeature/Tests/.gitkeep
  Projects/Features/BaseFeature/Tests/TargetTest.swift
  Projects/Features/RootFeature/Project.swift
Labels: ⚙️setting

#41 merge :: Base 세팅
  Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
  Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/App/Sources/Application/DI/AppComponent+LocalDataSource.swift
  Projects/App/Sources/Application/DI/AppComponent+RemoteDataSource.swift
  Projects/App/Sources/Application/DI/AppComponent+Repository.swift
  Projects/App/Sources/Application/DI/AppComponent+UseCase.swift
  Projects/Features/BaseFeature/Sources/BaseViewModel.swift
  Projects/Features/BaseFeature/Sources/Feature.swift
  Projects/Modules/ErrorModule/Derived/InfoPlists/ErrorModule-Info.plist
  Projects/Modules/ErrorModule/Derived/InfoPlists/ErrorModuleTests-Info.plist
  Projects/Modules/ErrorModule/Project.swift
  Projects/Modules/ErrorModule/Sources/DmsError.swift
  Projects/Modules/ErrorModule/Tests/.gitkeep
  Projects/Modules/ErrorModule/Tests/TargetTest.swift
  Projects/Modules/KeychainModule/Derived/InfoPlists/KeychainModule-Info.plist
  Projects/Modules/KeychainModule/Derived/InfoPlists/KeychainModuleTests-Info.plist
  Projects/Modules/KeychainModule/Project.swift
  Projects/Modules/KeychainModule/Sources/Keychain.swift
  Projects/Modules/KeychainModule/Sources/KeychainFake.swift
  Projects/Modules/KeychainModule/Sources/KeychainImpl.swift
  Projects/Modules/KeychainModule/Tests/.gitkeep
  Projects/Modules/KeychainModule/Tests/TargetTest.swift
  Projects/Modules/Utility/Project.swift
  Projects/Modules/Utility/Sources/DateUtil.swift
  Projects/Modules/Utility/Sources/Utility.swift
  Projects/Services/APIKit/Project.swift
  Projects/Services/APIKit/Sources/API.swift
  Projects/Services/APIKit/Sources/DmsAPI.swift
  Projects/Services/APIKit/Sources/Plugins/Jwt/JwtAuthorizable.swift
  Projects/Services/APIKit/Sources/Plugins/Jwt/JwtPlugin.swift
  Projects/Services/APIKit/Sources/Plugins/Jwt/TokenDTO.swift
  Projects/Services/APIKit/Tests/JwtPluginSpec.swift
  Projects/Services/APIKit/Tests/TestAPI.swift
  Projects/Services/DataMappingModule/Derived/InfoPlists/DataMappingModule-Info.plist
  Projects/Services/DataMappingModule/Derived/InfoPlists/DataMappingModuleTests-Info.plist
  Projects/Services/DataMappingModule/Project.swift
  Projects/Services/DataMappingModule/Sources/Base/NoResponse.swift
  Projects/Services/DataMappingModule/Tests/.gitkeep
  Projects/Services/DataMappingModule/Tests/TargetTest.swift
  Projects/Services/DomainModule/Project.swift
  Projects/Services/NetworkModule/Sources/Base/BaseRemoteDataSource.swift
  Projects/Services/NetworkModule/Sources/Feature.swift
  Tuist/Dependencies.swift
  graph.png
Labels: ✨feat

#46 merge :: Feature 생성 할때 일어날 수 있는 휴먼에러 걱정 하나를 제거?
  Scripts/generate_new_feature.py
Labels: ✨feat

#53 merge :: 디자인 시스템 - Toast
  Projects/UsertInterfaces/DesignSystem/Sources/Button/DMSButtonStyle.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Playground/DesignSystemPlaygroundView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Playground/Views/TextFieldPlaygroundView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Playground/Views/ToastPlaygroundView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Toast/DmsToast.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Toast/DmsToastStyle.swift
Labels: ✨feat

#49 merge :: 공통적으로 쓰일 backButton config하는 extension
  Projects/UsertInterfaces/DesignSystem/Sources/Extensions/View+configBackButton.swift
Labels: ✨feat

#52 merge :: dmsBackground Modifier
  Projects/UsertInterfaces/DesignSystem/Sources/Extensions/View+dmsBackground.swift
Labels: ✨feat

#56 merge :: Toast 자동 닫히기 로직 변경
  Projects/UsertInterfaces/DesignSystem/Sources/Toast/DmsToast.swift
Labels: ⚡️performance

#59 merge :: Auth API
  Projects/App/Sources/Application/DI/AppComponent.swift
  Projects/App/Sources/Application/DI/Auth/AppComponent+Auth.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Modules/ErrorModule/Sources/DmsError.swift
  Projects/Modules/ThirdPartyLib/Tests/TargetTest.swift
  Projects/Modules/Utility/Tests/TargetTest.swift
  Projects/Services/APIKit/Sources/AuthAPI.swift
  Projects/Services/APIKit/Sources/DmsAPI.swift
  Projects/Services/DataMappingModule/Sources/Auth/Request/EmailExistByAccountIDRequestDTO.swift
  Projects/Services/DataMappingModule/Sources/Auth/Request/SendAuthCodeRequestDTO.swift
  Projects/Services/DataMappingModule/Sources/Auth/Request/SigninRequestDTO.swift
  Projects/Services/DataMappingModule/Sources/Auth/Request/VerifyAuthCodeRequestDTO.swift
  Projects/Services/DataMappingModule/Sources/Auth/Response/CheckAccountIDIsExistResponseDTO.swift
  Projects/Services/DataMappingModule/Sources/Base/AuthCodeType.swift
  Projects/Services/DataModule/Sources/Auth/Repositories/Impl/AuthRepositoreImpl.swift
  Projects/Services/DataModule/Sources/Auth/Repositories/Stub/AuthRepositoryStub.swift
  Projects/Services/DataModule/Sources/Auth/UseCases/Impl/CheckAccountIDIsExistUseCaseImpl.swift
  Projects/Services/DataModule/Sources/Auth/UseCases/Impl/CheckEmailExistByAccountIDUseCaseImpl.swift
  Projects/Services/DataModule/Sources/Auth/UseCases/Impl/SendAuthCodeUseCaseImpl.swift
  Projects/Services/DataModule/Sources/Auth/UseCases/Impl/SigninUseCaseImpl.swift
  Projects/Services/DataModule/Sources/Auth/UseCases/Impl/VerifyAuthCodeUseCaseImpl.swift
  Projects/Services/DataModule/Sources/Repositories/RemoveMe2.swift
  Projects/Services/DataModule/Tests/Auth/Repository/AuthRepositoryImplSpec.swift
  Projects/Services/DataModule/Tests/Auth/UseCase/CheckAccountIDIsExistUseCaseImplSpec.swift
  Projects/Services/DataModule/Tests/Auth/UseCase/CheckEmailExistByAccountIDUseCaseImplSpec.swift
  Projects/Services/DataModule/Tests/Auth/UseCase/SendAuthCodeUseCaseImplSpec.swift
  Projects/Services/DataModule/Tests/Auth/UseCase/SigninUseCaseImplSpec.swift
  Projects/Services/DataModule/Tests/Auth/UseCase/VerifyAuthCodeUseCaseImplSpec.swift
  Projects/Services/DomainModule/Sources/Auth/Repository/AuthRepository.swift
  Projects/Services/DomainModule/Sources/Auth/UseCases/CheckAccountIDIsExistUseCase.swift
  Projects/Services/DomainModule/Sources/Auth/UseCases/CheckEmailExistByAccountIDUseCase.swift
  Projects/Services/DomainModule/Sources/Auth/UseCases/SendAuthCodeUseCase.swift
  Projects/Services/DomainModule/Sources/Auth/UseCases/SigninUseCase.swift
  Projects/Services/DomainModule/Sources/Auth/UseCases/VerifyAuthCodeUseCase.swift
  Projects/Services/DomainModule/Sources/Repositories/RemoveMe9.swift
  Projects/Services/DomainModule/Sources/UseCases/RemoveMe10.swift
  Projects/Services/NetworkModule/Sources/Auth/Remote/Impl/RemoteAuthDataSourceImpl.swift
  Projects/Services/NetworkModule/Sources/Auth/Remote/RemoteAuthDataSource.swift
  Projects/Services/NetworkModule/Sources/Auth/Remote/Stub/RemoteAuthDataSourceStub.swift
  Projects/Services/NetworkModule/Sources/Base/BaseRemoteDataSource.swift
  Projects/Services/NetworkModule/Sources/Extensions/AnyPublisher+map.swift
  Projects/Services/NetworkModule/Tests/Auth/Remote/RemoteAuthDataSourceImplSpec.swift
Labels: ✨feat, 🧪test

#63 merge :: DMSWideButton
  Projects/UsertInterfaces/DesignSystem/Sources/Button/Default/DMSButton.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Button/Default/DMSButtonStyle.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Button/Wide/DMSWideButton.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Button/Wide/DMSWideButtonStyle.swift
Labels: ✨feat

#64 merge :: Students API
  Projects/App/Sources/Application/DI/Students/AppComponent+Students.swift
  Projects/Modules/ErrorModule/Sources/DmsError.swift
  Projects/Services/APIKit/Sources/AuthAPI.swift
  Projects/Services/APIKit/Sources/StudentsAPI.swift
  Projects/Services/DataMappingModule/Sources/Base/NoResponse.swift
  Projects/Services/DataMappingModule/Sources/Students/Request/FindIDRequestDTO.swift
  Projects/Services/DataMappingModule/Sources/Students/Request/RenewalPasswordRequestDTO.swift
  Projects/Services/DataMappingModule/Sources/Students/Request/SignupRequestDTO.swift
  Projects/Services/DataMappingModule/Sources/Students/Response/FetchMyProfileResponseDTO.swift
  Projects/Services/DataMappingModule/Sources/Students/Response/FindIDResponseDTO.swift
  Projects/Services/DataModule/Sources/Students/Repositories/Impl/StudentsRepositoryImpl.swift
  Projects/Services/DataModule/Sources/Students/Repositories/Stub/StudentsRepositoryStub.swift
  Projects/Services/DataModule/Sources/Students/UseCases/Impl/CheckDuplicateAccountIDUseCaseImpl.swift
  Projects/Services/DataModule/Sources/Students/UseCases/Impl/CheckDuplicateEmailUseCaseImpl.swift
  Projects/Services/DataModule/Sources/Students/UseCases/Impl/FetchMyProfileUseCaseImpl.swift
  Projects/Services/DataModule/Sources/Students/UseCases/Impl/FindIDUseCaseImpl.swift
  Projects/Services/DataModule/Sources/Students/UseCases/Impl/RenewalPasswordUseCaseImpl.swift
  Projects/Services/DataModule/Sources/Students/UseCases/Impl/SignupUseCaseImpl.swift
  Projects/Services/DataModule/Tests/Students/Repository/StudentsRepositoryImplSpec.swift
  Projects/Services/DataModule/Tests/Students/UseCase/CheckDuplicateAccountIDUseCaseImplSpec.swift
  Projects/Services/DataModule/Tests/Students/UseCase/CheckDuplicateEmailUseCaseImplSpec.swift
  Projects/Services/DataModule/Tests/Students/UseCase/FetchMyProfileUseCaseImplSpec.swift
  Projects/Services/DataModule/Tests/Students/UseCase/FindIDUseCaseImplSpec.swift
  Projects/Services/DataModule/Tests/Students/UseCase/RenewalPasswordUseCaseImplSpec.swift
  Projects/Services/DataModule/Tests/Students/UseCase/SignupUseCaseImplSpec.swift
  Projects/Services/DomainModule/Sources/Entities/MyProfileEntity.swift
  Projects/Services/DomainModule/Sources/Entities/RemoveMe7.swift
  Projects/Services/DomainModule/Sources/Students/Repository/StudentsRepository.swift
  Projects/Services/DomainModule/Sources/Students/UseCases/CheckDuplicateAccountIDUseCase.swift
  Projects/Services/DomainModule/Sources/Students/UseCases/CheckDuplicateEmailUseCase.swift
  Projects/Services/DomainModule/Sources/Students/UseCases/FetchMyProfileUseCase.swift
  Projects/Services/DomainModule/Sources/Students/UseCases/FindIDUseCase.swift
  Projects/Services/DomainModule/Sources/Students/UseCases/RenewalPasswordUseCase.swift
  Projects/Services/DomainModule/Sources/Students/UseCases/SignupUseCase.swift
  Projects/Services/NetworkModule/Sources/Base/BaseRemoteDataSource.swift
  Projects/Services/NetworkModule/Sources/Students/Remote/Impl/DataTransfer/FetchMyProfileTransfer.swift
  Projects/Services/NetworkModule/Sources/Students/Remote/Impl/RemoteStudentsDataSourceImpl.swift
  Projects/Services/NetworkModule/Sources/Students/Remote/RemoteStudentsDataSource.swift
  Projects/Services/NetworkModule/Sources/Students/Remote/Stub/RemoteStudentsDataSourceStub.swift
  Projects/Services/NetworkModule/Tests/Students/Remote/RemoteStudentsDataSourceImplSpec.swift
Labels: ✨feat

#66 merge :: addCancellable이 파라미터로 받는 Publisher타입 변경
  Projects/Features/BaseFeature/Sources/BaseViewModel.swift
Labels: ♻️refactor

#68 merge :: 다수의 warning들해치우기
  Projects/Modules/ErrorModule/Sources/DmsError.swift
  Projects/Services/DataModule/Sources/Students/Repositories/Stub/StudentsRepositoryStub.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Extensions/View+dmsBackground.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Toast/DmsToast.swift
Labels: ♻️refactor

#72 merge :: School API
  Projects/Modules/ErrorModule/Sources/DmsError.swift
  Projects/Services/APIKit/Sources/SchoolAPI.swift
  Projects/Services/DataMappingModule/Sources/School/Response/CheckSchoolCodeResponseDTO.swift
  Projects/Services/DataMappingModule/Sources/School/Response/CheckSchoolQuestionResponseDTO.swift
  Projects/Services/DataMappingModule/Sources/School/Response/FetchSchoolListResponseDTO.swift
  Projects/Services/DataMappingModule/Sources/School/Response/SingleSchoolResponseDTO.swift
  Projects/Services/DataModule/Sources/School/Repositories/Impl/SchoolRepositoryImpl.swift
  Projects/Services/DataModule/Sources/School/Repositories/Stub/SchoolRepositoryStub.swift
  Projects/Services/DataModule/Sources/School/UseCase/Impl/CheckSchoolCodeUseCaseImpl..swift
  Projects/Services/DataModule/Sources/School/UseCase/Impl/CheckSchoolQuestionUseCaseImpl.swift
  Projects/Services/DataModule/Sources/School/UseCase/Impl/FetchSchoolListUseCaseImpl.swift
  Projects/Services/DataModule/Sources/School/UseCase/Impl/FetchSchoolQuestionUseCaseImpl.swift
  Projects/Services/DomainModule/Sources/Entities/CheckSchoolCodeEntity.swift
  Projects/Services/DomainModule/Sources/Entities/CheckSchoolQuestionEntity.swift
  Projects/Services/DomainModule/Sources/Entities/FetchSchoolListEntity.swift
  Projects/Services/DomainModule/Sources/Entities/SchoolEntity.swift
  Projects/Services/DomainModule/Sources/School/Repository/SchoolRepository.swift
  Projects/Services/DomainModule/Sources/School/UseCases/CheckSchoolCodeUseCase.swift
  Projects/Services/DomainModule/Sources/School/UseCases/CheckSchoolQuestionUseCase.swift
  Projects/Services/DomainModule/Sources/School/UseCases/FetchSchoolListUseCase.swift
  Projects/Services/DomainModule/Sources/School/UseCases/GetSchoolQuestionUseCase.swift
  Projects/Services/NetworkModule/Sources/School/Remote/Impl/DataTransfer/FetchSchoolListTransfer.swift
  Projects/Services/NetworkModule/Sources/School/Remote/Impl/DataTransfer/SingleSchoolListTransfer.swift
  Projects/Services/NetworkModule/Sources/School/Remote/Impl/RemoteSchoolDataSourceImpl.swift
  Projects/Services/NetworkModule/Sources/School/Remote/RemoteSchoolDataSource.swift
  Projects/Services/NetworkModule/Sources/School/Remote/Stub/RemoteSchoolDataSourceStub.swift
  Projects/Services/NetworkModule/Sources/Students/Remote/Stub/RemoteStudentsDataSourceStub.swift
Labels: ✨feat

#74 merge :: 휴면 에러로 작성되지 않은 School Di 작성
  Projects/App/Sources/Application/DI/School/AppComponent+School.swift
Labels: ✨feat, 👾bug

#86 merge :: MainTabView
  Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
  Projects/App/Sources/Application/DI/AppComponent.swift
  Projects/App/Sources/Application/DMSApp.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Features/MainTabFeature/Derived/InfoPlists/MainTabFeature-Info.plist
  Projects/Features/MainTabFeature/Derived/InfoPlists/MainTabFeatureTests-Info.plist
  Projects/Features/MainTabFeature/Project.swift
  Projects/Features/MainTabFeature/Sources/MainTabComponent.swift
  Projects/Features/MainTabFeature/Sources/MainTabView.swift
  Projects/Features/MainTabFeature/Tests/TargetTests.swift
  Projects/Features/RootFeature/Project.swift
Labels: ✨feat

#87 merge :: Dms Bottom Sheet Modifier
  Projects/App/Sources/Application/DMSApp.swift
  Projects/UsertInterfaces/DesignSystem/Sources/BottomSheet/DmsBottomSheet.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Extensions/View+cornerRadius.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Extensions/View+dmsBackButton.swift
Labels: ✨feat

#77 merge :: (#44) Signup - AuthenticationCode UI
  Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
  Projects/App/Sources/Application/DI/AppComponent.swift
  Projects/App/Sources/Application/DMSApp.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Features/RootFeature/Project.swift
  Projects/Features/SignupFeature/Derived/InfoPlists/SignupFeature-Info.plist
  Projects/Features/SignupFeature/Derived/InfoPlists/SignupFeatureTests-Info.plist
  Projects/Features/SignupFeature/Project.swift
  Projects/Features/SignupFeature/Sources/PasscodeView.swift
  Projects/Features/SignupFeature/Sources/SchoolCodeComponent.swift
  Projects/Features/SignupFeature/Sources/SchoolCodeView.swift
  Projects/Features/SignupFeature/Sources/SchoolCodeViewModel.swift
  Projects/Features/SignupFeature/Tests/TargetTests.swift
Labels: ✨feat

#91 merge :: Design System PassCodeview
  Projects/Features/SignupFeature/Sources/SchoolCodeView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/BottomSheet/DMSBottomSheet.swift
  Projects/UsertInterfaces/DesignSystem/Sources/PassCode/DMSPassCodeView.swift
Labels: ✨feat

#94 merge :: MealAPI 작업
  Projects/App/Sources/Application/DI/Meal/AppComponent+Meal.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Features/HomeFeature/Sources/HomeComponent.swift
  Projects/Features/HomeFeature/Sources/HomeView.swift
  Projects/Features/HomeFeature/Sources/HomeViewModel.swift
  Projects/Services/APIKit/Sources/MealAPI.swift
  Projects/Services/DataMappingModule/Sources/Meals/Response/FetchMealListResponseDTO.swift
  Projects/Services/DataMappingModule/Sources/Meals/Response/SingleMealResponseDTO.swift
  Projects/Services/DataModule/Sources/Meal/Repositories/Impl/MealRepositoryImpl.swift
  Projects/Services/DataModule/Sources/Meal/UseCases/Impl/FetchMealListUseCaseImpl.swift
  Projects/Services/DomainModule/Sources/Meals/Repository/MealRepository.swift
  Projects/Services/DomainModule/Sources/Meals/UseCases/FetchMealListUseCase.swift
  Projects/Services/NetworkModule/Sources/Meal/Remote/Impl/DataTransfer/FetchMealListTransfer.swift
  Projects/Services/NetworkModule/Sources/Meal/Remote/Impl/RemoteMealDataSourceImpl.swift
  Projects/Services/NetworkModule/Sources/Meal/Remote/RemoteMealDataSource.swift
  Projects/Services/NetworkModule/Sources/Meal/Remote/Stub/RemoteMealDataSourceStub.swift
Labels: ✨feat

#96 merge :: 회원가입 - 인증 이메일 입력 Feature
  Projects/App/Sources/Application/DI/AppComponent.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Features/BaseFeature/Sources/EnvironmentValues/RootPresentationMode.swift
  Projects/Features/BaseFeature/Sources/HideKeyboard.swift
  Projects/Features/SigninFeature/Sources/SigninView.swift
  Projects/Features/SigninFeature/Sources/SigninViewModel.swift
  Projects/Features/SigninFeature/Tests/SigninViewModelSpec.swift
  Projects/Features/SignupFeature/Sources/SchoolCode/SchoolCodeComponent.swift
  Projects/Features/SignupFeature/Sources/SchoolCode/SchoolCodeView.swift
  Projects/Features/SignupFeature/Sources/SchoolCode/SchoolCodeViewModel.swift
  Projects/Features/SignupFeature/Sources/SignupEmailAuthCodeVerify/EmailAuthCodeVerifyComponent.swift
  Projects/Features/SignupFeature/Sources/SignupEmailAuthCodeVerify/EmailAuthCodeVerifyView.swift
  Projects/Features/SignupFeature/Sources/SignupEmailAuthCodeVerify/EmailAuthCodeVerifyViewModel.swift
  Projects/Features/SignupFeature/Sources/SignupEmailAuthCodeVerify/SignupEmailAuthCodeVerifyParam.swift
  Projects/Features/SignupFeature/Sources/SignupEmailVerify/SignupEmailVerifyComponent.swift
  Projects/Features/SignupFeature/Sources/SignupEmailVerify/SignupEmailVerifyParam.swift
  Projects/Features/SignupFeature/Sources/SignupEmailVerify/SignupEmailVerifyView.swift
  Projects/Features/SignupFeature/Sources/SignupEmailVerify/SignupEmailVerifyViewModel.swift
  Projects/Modules/Utility/Sources/RegexUtil.swift
  Projects/UsertInterfaces/DesignSystem/Sources/PassCode/DMSPassCodeView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/TextField/Floating/DMSFloatingTextField.swift
Labels: ✨feat

#100 merge :: Files API
  Projects/App/Sources/Application/DI/Files/AppComponent+Files.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Services/APIKit/Sources/DmsAPI.swift
  Projects/Services/APIKit/Sources/FilesAPI.swift
  Projects/Services/DataMappingModule/Sources/Files/Response/UploadFileResponseDTO.swift
  Projects/Services/DataModule/Sources/Files/Repositories/FilesRepositoryImpl.swift
  Projects/Services/DataModule/Sources/Files/UseCases/UploadFileUseCaseImpl.swift
  Projects/Services/DomainModule/Sources/Files/Repository/FilesRepository.swift
  Projects/Services/DomainModule/Sources/Files/UseCases/UploadFileUseCase.swift
  Projects/Services/NetworkModule/Sources/Files/Remote/Impl/RemoteFilesDataSourceImpl.swift
  Projects/Services/NetworkModule/Sources/Files/Remote/RemoteFilesDataSource.swift
  Projects/Services/NetworkModule/Sources/Files/Remote/Stub/RemoteFilesDataSourceStub.swift
Labels: ✨feat

#95 merge :: SchoolConfirmationQuestions UI
  Projects/App/Sources/Application/DI/AppComponent.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Features/SignupFeature/Sources/SchoolCode/SchoolCodeView.swift
  Projects/Features/SignupFeature/Sources/SchoolCode/SchoolCodeViewModel.swift
  Projects/Features/SignupFeature/Sources/SchoolConfirmationQuestions/SchoolConfirmationQuestionsComponent.swift
  Projects/Features/SignupFeature/Sources/SchoolConfirmationQuestions/SchoolConfirmationQuestionsView.swift
  Projects/Features/SignupFeature/Sources/SchoolConfirmationQuestions/SchoolConfirmationQuestionsViewModel.swift
Labels: ✨feat

#104 merge :: 약관동의 페이지
  Projects/App/Sources/Application/DI/AppComponent.swift
  Projects/App/Sources/Application/DMSApp.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Support/Info.plist
  Projects/Features/HomeFeature/Sources/Component/NoticeView.swift
  Projects/Features/SignupFeature/Sources/SignupTerms/SignupTermsComponent.swift
  Projects/Features/SignupFeature/Sources/SignupTerms/SignupTermsView.swift
  Projects/Features/SignupFeature/Sources/SignupTerms/SignupTermsViewModel.swift
  Projects/UsertInterfaces/DesignSystem/Sources/WebView/DMSWebView.swift
Labels: ✨feat

#106 merge :: 회원가입 - 비밀번호 설정 페이지
  Projects/App/Sources/Application/DI/AppComponent.swift
  Projects/App/Sources/Application/DMSApp.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Features/SignupFeature/Sources/SignupPassword/SignupPasswordComponent.swift
  Projects/Features/SignupFeature/Sources/SignupPassword/SignupPasswordView.swift
  Projects/Features/SignupFeature/Sources/SignupPassword/SignupPasswordViewModel.swift
Labels: ✨feat
