Repository team-aliens/DMS-iOS, pull requests merged in 2023-03, with the labels that each got.

#184 merge :: Kingfisher 적용
  Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Features/MyPageFeature/Sources/MyPage/MyPageView.swift
  Projects/Modules/FeatureThirdPartyLib/Project.swift
  Tuist/Dependencies.swift
Labels: ⚡️performance

#186 refactor :: 잔류 신청 버튼 bottom padding 줄이기
  Projects/Features/RemainApplyFeature/Sources/RemainApplyView.swift
Labels: ♻️refactor

#189 merge :: 잔류 신청 및 ApplyPage 잔 버그 수정
  Projects/Features/RemainApplyFeature/Sources/Component/RemainApplyListCellView.swift
  Projects/Features/RemainApplyFeature/Sources/RemainApplyView.swift
  Projects/Features/RemainApplyFeature/Sources/RemainApplyViewModel.swift
Labels: ♻️refactor, 👾bug

#196 (#195) 스크롤 refreshControl 추가
  Projects/Features/ApplyFeature/Sources/ApplyPage/ApplyPageView.swift
  Projects/Features/ApplyFeature/Sources/ApplyPage/ApplyPageViewModel.swift
  Projects/Features/MyPageFeature/Sources/MyPage/MyPageView.swift
  Projects/Features/MyPageFeature/Sources/MyPage/MyPageViewModel.swift
  Projects/Features/NoticeFeature/Sources/NoticeList/NoticeListView.swift
  Projects/Features/NoticeFeature/Sources/NoticeList/NoticeListViewModel.swift
  Projects/Features/RemainApplyFeature/Sources/RemainApplyView.swift
  Projects/Features/RemainApplyFeature/Sources/RemainApplyViewModel.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyRoomListView.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyRoomListViewModel.swift
Labels: ✨feat

#206 UI 버그 코드 리팩토링
  Projects/Features/ApplyFeature/Sources/ApplyPage/ApplyPageView.swift
  Projects/Features/MainTabFeature/Sources/MainTabView.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyRoomListView.swift
  Projects/Services/DataMappingModule/Sources/Base/DmsFeaturesResponseDTO.swift
  Projects/Services/DataModule/Sources/Auth/Repositories/Stub/AuthRepositoryStub.swift
  Projects/Services/DataModule/Sources/Auth/UseCases/Fake/SigninUseCaseFake.swift
  Projects/Services/DomainModule/Sources/Entities/DmsFeatures.swift
  Projects/Services/NetworkModule/Sources/Auth/Remote/Stub/RemoteAuthDataSourceStub.swift
  Projects/Services/NetworkModule/Sources/Base/DataTransfer/DmsFeaturesDataTransfer.swift
  Projects/UsertInterfaces/DesignSystem/Sources/ImagePicker/ImagePicker.swift
Labels: ♻️refactor

#213 merge :: 신청 화면 버그 수정
  Projects/Features/RemainApplyFeature/Sources/RemainApplyView.swift
  Projects/Features/RemainApplyFeature/Sources/RemainApplyViewModel.swift
  Projects/Features/StudyRoomFeature/Sources/StudyRoomDetail/StudyRoomDetailView.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyRoomListView.swift
  Projects/UsertInterfaces/DesignSystem/Resources/PrimaryColor.xcassets/Darken-1.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/PrimaryColor.xcassets/Lighten-1.colorset/Contents.json
Labels: 👾bug

#211 feat :: 회원가입 직후 탭바에서 신청 탭이 사라지는 오류 해결
  Projects/Features/SignupFeature/Sources/SignupTerms/SignupTermsParam.swift
  Projects/Features/SignupFeature/Sources/SignupTerms/SignupTermsView.swift
  Projects/Features/SignupFeature/Sources/SignupTerms/SignupTermsViewModel.swift
  Projects/Modules/ErrorModule/Sources/DmsError.swift
  Projects/Services/APIKit/Sources/StudentsAPI.swift
  Projects/Services/DataMappingModule/Sources/Base/DmsFeaturesResponseDTO.swift
  Projects/Services/DataModule/Sources/Auth/Repositories/Stub/AuthRepositoryStub.swift
  Projects/Services/DataModule/Sources/Auth/UseCases/Fake/SigninUseCaseFake.swift
  Projects/Services/DataModule/Sources/Students/Repositories/Impl/StudentsRepositoryImpl.swift
  Projects/Services/DataModule/Sources/Students/Repositories/Stub/StudentsRepositoryStub.swift
  Projects/Services/DataModule/Sources/Students/UseCases/Fake/SignupUseCaseFake.swift
  Projects/Services/DataModule/Sources/Students/UseCases/Impl/SignupUseCaseImpl.swift
  Projects/Services/DataModule/Tests/Auth/Repository/AuthRepositoryImplSpec.swift
  Projects/Services/DataModule/Tests/Auth/UseCase/SigninUseCaseImplSpec.swift
  Projects/Services/DataModule/Tests/Students/Repository/StudentsRepositoryImplSpec.swift
  Projects/Services/DataModule/Tests/Students/UseCase/SignupUseCaseImplSpec.swift
  Projects/Services/DomainModule/Sources/Entities/DmsFeatures.swift
  Projects/Services/DomainModule/Sources/Students/Repository/StudentsRepository.swift
  Projects/Services/DomainModule/Sources/Students/UseCases/SignupUseCase.swift
  Projects/Services/NetworkModule/Sources/Auth/Remote/Stub/RemoteAuthDataSourceStub.swift
  Projects/Services/NetworkModule/Sources/Base/DataTransfer/DmsFeaturesDataTransfer.swift
  Projects/Services/NetworkModule/Sources/Students/Remote/Impl/RemoteStudentsDataSourceImpl.swift
  Projects/Services/NetworkModule/Sources/Students/Remote/RemoteStudentsDataSource.swift
  Projects/Services/NetworkModule/Sources/Students/Remote/Stub/RemoteStudentsDataSourceStub.swift
  Projects/Services/NetworkModule/Tests/Auth/Remote/RemoteAuthDataSourceImplSpec.swift
  Projects/Services/NetworkModule/Tests/Students/Remote/RemoteStudentsDataSourceImplSpec.swift
Labels: ✨feat, ♻️refactor

#218 feat :: 공지 위젯 fixedSize 설정 변경
  Projects/App/AppExtension/Sources/Notice/DMSNoticeEntryView.swift
Labels: ♻️refactor

#224 215 studyroom application time list UI
  Projects/Features/HomeFeature/Sources/HomeView.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyRoomListView.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyRoomListViewModel.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyroomTimeListView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/BottomSheet/DMSBottomSheet.swift
Labels: ✨feat

#226 🔀 :: CI 고치기 - bundle version
  Projects/App/AppExtension/Support/Widget-Info.plist
  Projects/App/Support/Info.plist
  Projects/App/WatchApp/Support/Extension-Info.plist
  Projects/App/WatchApp/Support/Info.plist
Labels: 👾bug

#227 자습실 이용 시간 목록 API 연동
  Projects/App/Sources/Application/DI/StudyRooms/AppComponent+StudyRooms.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/WatchApp/Support/Info.plist
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyRoomListComponent.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyRoomListView.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyRoomListViewModel.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyroomTimeList/StudyroomTimeListCellView.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyroomTimeList/StudyroomTimeListView.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyroomTimeListView.swift
  Projects/Services/APIKit/Sources/StudyRoomsAPI.swift
  Projects/Services/DataMappingModule/Sources/StudyRooms/Response/FetchStudyRoomTimeListResponseDTO.swift
  Projects/Services/DataMappingModule/Sources/StudyRooms/Response/TimeSlotsResponseDTO.swift
  Projects/Services/DataModule/Sources/StudyRooms/Repositories/Impl/StudyRoomsRepositoryImpl.swift
  Projects/Services/DataModule/Sources/StudyRooms/UseCases/Impl/FetchStudyroomTimeListUseCaseImpl.swift
  Projects/Services/DomainModule/Sources/Entities/StudyroomTimeListEntity.swift
  Projects/Services/DomainModule/Sources/Entities/TimeSlotsEntity.swift
  Projects/Services/DomainModule/Sources/Remains/Repository/RemainsRepository.swift
  Projects/Services/DomainModule/Sources/StudyRooms/Repository/StudyRoomsRepository.swift
  Projects/Services/DomainModule/Sources/StudyRooms/UseCases/FetchStudyroomTimeListUseCase.swift
  Projects/Services/NetworkModule/Sources/StudyRooms/Remote/Impl/DataTransfer/FetchStudyroomTimeListDataTransfer.swift
  Projects/Services/NetworkModule/Sources/StudyRooms/Remote/Impl/RemoteStudyRoomsDataSourceImpl.swift
  Projects/Services/NetworkModule/Sources/StudyRooms/Remote/RemoteStudyRoomsDataSource.swift
Labels: ✨feat

#230 자습실 목록 보기 UI 퍼블리싱 및 API 수정
  Projects/Features/StudyRoomFeature/Sources/Component/StudyRoomListCellView.swift
  Projects/Features/StudyRoomFeature/Sources/StudyRoomDetail/StudyRoomDetailComponent.swift
  Projects/Features/StudyRoomFeature/Sources/StudyRoomDetail/StudyRoomDetailViewModel.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyRoomListView.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyRoomListViewModel.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyroomTimeList/StudyroomTimeListView.swift
  Projects/Services/APIKit/Sources/StudyRoomsAPI.swift
  Projects/Services/DataModule/Sources/StudyRooms/Repositories/Impl/StudyRoomsRepositoryImpl.swift
  Projects/Services/DataModule/Sources/StudyRooms/UseCases/Impl/ApplyStudyRoomSeatUseCaseImpl.swift
  Projects/Services/DataModule/Sources/StudyRooms/UseCases/Impl/CancelStudyRoomSeatUseCaseImpl.swift
  Projects/Services/DataModule/Sources/StudyRooms/UseCases/Impl/FetchDetailStudyRoomUseCaseImpl.swift
  Projects/Services/DataModule/Sources/StudyRooms/UseCases/Impl/FetchStudyRoomListUseCaseImpl.swift
  Projects/Services/DomainModule/Sources/StudyRooms/Repository/StudyRoomsRepository.swift
  Projects/Services/DomainModule/Sources/StudyRooms/UseCases/ApplyStudyRoomSeatUseCase.swift
  Projects/Services/DomainModule/Sources/StudyRooms/UseCases/CancelStudyRoomSeatUseCase.swift
  Projects/Services/DomainModule/Sources/StudyRooms/UseCases/FetchDetailStudyRoomUseCase.swift
  Projects/Services/DomainModule/Sources/StudyRooms/UseCases/FetchStudyRoomListUseCase.swift
  Projects/Services/NetworkModule/Sources/StudyRooms/Remote/Impl/RemoteStudyRoomsDataSourceImpl.swift
  Projects/Services/NetworkModule/Sources/StudyRooms/Remote/RemoteStudyRoomsDataSource.swift
Labels: ✨feat, ♻️refactor

#236 상/벌점 off 모드 구현
  Projects/Features/MyPageFeature/Sources/MyPage/MyPageView.swift
  Projects/Services/DataMappingModule/Sources/Points/FetchPointListResponseDTO.swift
Labels: ✨feat

#235 날짜 포맷 변경으로 인한 DateFormatter 코드 리팩토링
  Projects/Features/NoticeFeature/Sources/Detail/NoticeDetailViewModel.swift
  Projects/Features/RemainApplyFeature/Sources/RemainApplyViewModel.swift
  Projects/Features/StudyRoomFeature/Sources/StudyRoomDetail/StudyRoomDetailViewModel.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyRoomListViewModel.swift
  Projects/Modules/Utility/Sources/DateUtil.swift
  Projects/Services/DomainModule/Sources/Entities/RemainsAvailableTimeEntity.swift
  Projects/Services/DomainModule/Sources/Entities/StudyAvailableTimeEntity.swift
  Projects/Services/NetworkModule/Sources/Notice/Remote/Impl/DataTransfer/FetchNoticeListTransfer.swift
  Projects/Services/NetworkModule/Sources/Remains/Remote/Impl/DataTransfer/FetchRemainsAvailableTimeDataTransfer.swift
  Projects/Services/NetworkModule/Sources/StudyRooms/Remote/Impl/DataTransfer/FetchStudyAvailableTimeDataTransfer.swift
Labels: ♻️refactor
