Repository team-aliens/DMS-iOS, pull requests merged in 2023-04, with the labels that each got.

#240 refactor :: 자습실 자리 종류 보기 API에 QueryString 추가
  Projects/Features/MyPageFeature/Sources/MyPage/MyPageView.swift
  Projects/Features/StudyRoomFeature/Sources/StudyRoomDetail/StudyRoomDetailViewModel.swift
  Projects/Services/APIKit/Sources/StudyRoomsAPI.swift
  Projects/Services/DataModule/Sources/StudyRooms/Repositories/Impl/StudyRoomsRepositoryImpl.swift
  Projects/Services/DataModule/Sources/StudyRooms/UseCases/Impl/FetchSeatTypesUseCaseImpl.swift
  Projects/Services/DomainModule/Sources/StudyRooms/Repository/StudyRoomsRepository.swift
  Projects/Services/DomainModule/Sources/StudyRooms/UseCases/FetchSeatTypesUseCase.swift
  Projects/Services/NetworkModule/Sources/StudyRooms/Remote/Impl/RemoteStudyRoomsDataSourceImpl.swift
  Projects/Services/NetworkModule/Sources/StudyRooms/Remote/RemoteStudyRoomsDataSource.swift
Labels: ♻️refactor

#245 자습실 신청 이름 오류 고치기
  Projects/Features/StudyRoomFeature/Sources/StudyRoomDetail/Component/StudyRoomSeatDetailView.swift
  Projects/Features/StudyRoomFeature/Sources/StudyRoomDetail/StudyRoomDetailView.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyRoomListViewModel.swift
  Projects/Services/DataMappingModule/Sources/Enum/SeatStatusType.swift
Labels: 💬need discussion, ♻️refactor, 👾bug

#247 fix :: 자습실 자리 취소 시 전체 자습실 취소 오류 해결
  Projects/Features/StudyRoomFeature/Sources/StudyRoomDetail/StudyRoomDetailView.swift
  Projects/Features/StudyRoomFeature/Sources/StudyRoomDetail/StudyRoomDetailViewModel.swift
  Projects/Services/APIKit/Sources/StudyRoomsAPI.swift
  Projects/Services/DataModule/Sources/StudyRooms/Repositories/Impl/StudyRoomsRepositoryImpl.swift
  Projects/Services/DataModule/Sources/StudyRooms/UseCases/Impl/CancelStudyRoomSeatUseCaseImpl.swift
  Projects/Services/DomainModule/Sources/StudyRooms/Repository/StudyRoomsRepository.swift
  Projects/Services/DomainModule/Sources/StudyRooms/UseCases/CancelStudyRoomSeatUseCase.swift
  Projects/Services/NetworkModule/Sources/StudyRooms/Remote/Impl/RemoteStudyRoomsDataSourceImpl.swift
  Projects/Services/NetworkModule/Sources/StudyRooms/Remote/RemoteStudyRoomsDataSource.swift
Labels: ✨feat, ♻️refactor, 👾bug

#243 🔀 :: 재사용 모듈 productType 변경
  Projects/Features/BaseFeature/Project.swift
  Projects/Modules/ErrorModule/Project.swift
  Projects/Modules/Utility/Project.swift
  Projects/Services/DataMappingModule/Project.swift
  Projects/Services/DomainModule/Project.swift
  graph.png
Labels: ⚡️performance, ⚙️setting

#250 merge :: (#249) study room 시간 자동 선택
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyRoomListView.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyRoomListViewModel.swift
  Projects/Features/StudyRoomFeature/Sources/StudyroomApplication/StudyroomTimeList/StudyroomTimeListView.swift
Labels: ✨feat

#222 merge :: 급식 뷰 날짜 변경 시 아침 급식으로 변경
  Projects/Features/HomeFeature/Sources/Component/MealCarouselView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Carousel/Carousel.swift
Labels: ✨feat

#255 merge :: 폰트 register 개선
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Typography/DMSFont.swift
Labels: ⚡️performance
